/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Techy Minecraft Server API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateChangelogBodyChangesItem } from "./createChangelogBodyChangesItem";
export interface CreateChangelogBody {
    version: string;
    title: string;
    changes: CreateChangelogBodyChangesItem[];
}
//# sourceMappingURL=createChangelogBody.d.ts.map