/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Techy Minecraft Server API
 * OpenAPI spec version: 0.1.0
 */
export interface ForumStats {
    totalThreads: number;
    totalPosts: number;
    totalMembers: number;
    newestMember?: string;
    onlineNow: number;
}
//# sourceMappingURL=forumStats.d.ts.map