/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Techy Minecraft Server API
 * OpenAPI spec version: 0.1.0
 */
export type GetLeaderboardType = (typeof GetLeaderboardType)[keyof typeof GetLeaderboardType];
export declare const GetLeaderboardType: {
    readonly kills: "kills";
    readonly deaths: "deaths";
    readonly playtime: "playtime";
    readonly votes: "votes";
    readonly money: "money";
};
//# sourceMappingURL=getLeaderboardType.d.ts.map