/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Techy Minecraft Server API
 * OpenAPI spec version: 0.1.0
 */
export interface ServerStatus {
    online: boolean;
    playerCount: number;
    maxPlayers: number;
    motd?: string;
    version?: string;
    onlinePlayers?: string[];
}
//# sourceMappingURL=serverStatus.d.ts.map