/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Techy Minecraft Server API
 * OpenAPI spec version: 0.1.0
 */
import type { StaffApplicationStatus } from "./staffApplicationStatus";
export interface StaffApplication {
    id: number;
    applicantName: string;
    position: string;
    age: number;
    experience: string;
    whyJoin: string;
    availability?: string;
    status: StaffApplicationStatus;
    adminNote?: string;
    createdAt: string;
}
//# sourceMappingURL=staffApplication.d.ts.map