/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Techy Minecraft Server API
 * OpenAPI spec version: 0.1.0
 */
export type StaffApplicationStatus = (typeof StaffApplicationStatus)[keyof typeof StaffApplicationStatus];
export declare const StaffApplicationStatus: {
    readonly pending: "pending";
    readonly accepted: "accepted";
    readonly rejected: "rejected";
};
//# sourceMappingURL=staffApplicationStatus.d.ts.map