kind = "web"
previewPath = "/"
title = "techy Minecraft Server"
version = "1.0.0"
id = "artifacts/techy-mc"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22419

[services.development]
run = "pnpm --filter @workspace/techy-mc run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/techy-mc", "run", "build" ]
publicDir = "artifacts/techy-mc/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22419"
BASE_PATH = "/"
